---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: interfacemaps.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  names:
    kind: InterfaceMap
    listKind: InterfaceMapList
    plural: interfacemaps
    singular: interfacemap
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: array
            items:
              type: object
              properties:
                interface:
                  type: string
                network:
                  type: string
# ---
# apiVersion: "k8s.cni.cncf.io/v1"
# kind: InterfaceMap
# metadata:
#   name: hostfoo
# spec:
#   - interface: "eth0"
#     network: "blue"
#   - interface: "ens4"
#     network: "red"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: surveyor-cni
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
    verbs:
      - get
      - update
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: surveyor-cni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: surveyor-cni
subjects:
- kind: ServiceAccount
  name: surveyor-cni
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: surveyor-cni
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-surveyor-cni-ds
  namespace: kube-system
  labels:
    tier: node
    app: surveyor-cni
    name: surveyor-cni
spec:
  selector:
    matchLabels:
      name: surveyor-cni
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: surveyor-cni
        name: surveyor-cni
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      serviceAccountName: surveyor-cni
      containers:
      - name: kube-surveyor-cni
        image: docker.io/dougbtv/surveyor-cni:gen1
        imagePullPolicy: Always
        command: ["/entrypoint.sh"]
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: socketpath
          mountPath: /host/var/run/surveyor-cni
      initContainers:
        - name: install-surveyor-cni-binary
          image: docker.io/dougbtv/surveyor-cni:latest
          command:
            - "cp"
            - "/usr/src/surveyor-cni/bin/chainsaw"
            - "/host/opt/cni/bin/chainsaw"
          resources:
            requests:
              cpu: "10m"
              memory: "15Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
              mountPropagation: Bidirectional
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: socketpath
          hostPath:
            path: /var/run/surveyor-cni
            type: DirectoryOrCreate