---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: test-surveyor
spec:
  config: '{
    "cniVersion": "0.4.0",
    "name": "test-surveyor-chain",
    "plugins": [{
      "type": "surveyor",
      "foo": "bar"
    }]
  }'
---
apiVersion: v1
kind: Pod
metadata:
  name: surveyortestpod
  annotations:
    k8s.v1.cni.cncf.io/networks: test-surveyor
    k8s.v1.cni.cncf.io/surveyor: >
      ["ip route","  ip addr"]
spec:
  containers:
  - name: surveyortestpod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine