---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: test-surveyor
spec:
  config: '{
    "cniVersion": "0.4.0",
    "name": "test-surveyor-chain",
    "plugins": [{
      "type": "surveyor",
      "foo": "bar",
      "network": "red",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [{
          "address": "10.10.0.1/24"
        }]
      }
    }]
  }'
---
apiVersion: v1
kind: Pod
metadata:
  name: surveyortestpod
  annotations:
    k8s.v1.cni.cncf.io/networks: test-surveyor
spec:
  containers:
  - name: surveyortestpod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine