/*
Copyright 2023 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	k8scnicncfiov1 "github.com/dougbtv/surveyor-cni/pkg/apis/k8s.cni.cncf.io/v1"
	versioned "github.com/dougbtv/surveyor-cni/pkg/client/clientset/versioned"
	internalinterfaces "github.com/dougbtv/surveyor-cni/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/dougbtv/surveyor-cni/pkg/client/listers/k8s.cni.cncf.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// InterfaceMapInformer provides access to a shared informer and lister for
// InterfaceMaps.
type InterfaceMapInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.InterfaceMapLister
}

type interfaceMapInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewInterfaceMapInformer constructs a new informer for InterfaceMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewInterfaceMapInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredInterfaceMapInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredInterfaceMapInformer constructs a new informer for InterfaceMap type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredInterfaceMapInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1().InterfaceMaps(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1().InterfaceMaps(namespace).Watch(context.TODO(), options)
			},
		},
		&k8scnicncfiov1.InterfaceMap{},
		resyncPeriod,
		indexers,
	)
}

func (f *interfaceMapInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredInterfaceMapInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *interfaceMapInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&k8scnicncfiov1.InterfaceMap{}, f.defaultInformer)
}

func (f *interfaceMapInformer) Lister() v1.InterfaceMapLister {
	return v1.NewInterfaceMapLister(f.Informer().GetIndexer())
}
